<a href="https://colab.research.google.com/github/engineercha/Python-study/blob/master/pj_%EC%97%B0%EB%A6%BD%EC%9D%BC%EC%B0%A8%EB%B0%A9%EC%A0%95%EC%8B%9D_%EA%B3%84%EC%82%B0%EA%B8%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [88]:
import numpy as np
import matplotlib.pyplot as plt
import random

In [89]:
#x나 y의 계수가 1인 일차방정식 a
while True:
  a=np.array([random.randrange(11) for i in range(3)])
  if 1 in a[:2]: break
a

array([ 1, 10,  9])

In [90]:
#일차방정식 b
while True:
  b=np.array([random.randrange(11) for i in range(3)])
  if list(b).count(0) < 2: break
b

array([ 5, 10,  7])

In [91]:
#Linear system
print(f'{a[0]}x + {a[1]}y = {a[2]}')
print(f'{b[0]}x + {b[1]}y = {b[2]}')

1x + 10y = 9
5x + 10y = 7


In [92]:
#Augmented matrix
c=np.vstack([a, b])
c

array([[ 1, 10,  9],
       [ 5, 10,  7]])

##Random
- np.random.**randint** 균일 분포의 정수 난수 1개 생성
- np.random.**rand** 0~1 균일 분포에서 난수 matrix array 생성
- np.random.**randn** 가우시안 표준정규분포에서에서 난수 matrix array 생성

random.shuffle(기존의 데이터 순서 바꾸기), random.choice(기존의 데이터 중 샘플링), unique(중복되지 않은 값 리스트 출력)

In [93]:
idx=[i for i in range(-10,11) if i!=0]
idx.reverse()
for i in idx:
  A=a*i
  B=b*i
  constant=i
  if A[0]==b[0] or A[1]==b[1]:
    sol=A-b
    break
  elif A[0]==-b[0] or A[1]==-b[1]:
    sol=A+b
    break
  elif B[0]==a[0] or B[1]==a[1]:
    sol=B-a
    break
  elif B[0]==-a[0] or B[1]==-a[1]:
    sol=B+a
    break
print(constant)
sol

5


array([ 0, 40, 38])

In [94]:
#해가 없는 경우
if a[0]!=0 and b[0]!=0:
    a_slope=a[1]/a[0]
    b_slope=b[1]/b[1]
    if a_slope==b_slope and a[2]==b[2]: print("해가 무수히 많다")
    elif a_slope==b_slope and a[2]!=b[2]: print("해가 없다(두 직선이 평행이다)")

In [95]:
#해가 있는 경우: a나 b가 축에 평행하는 직선
if a[0]==0: y=a[2]
elif a[1]==0: x=a[2]
if b[0]==0: y=b[2]
elif b[1]==0: x=b[2]
print(f'x={x}, y={y}')

x=-0.7777777777777786, y=2.4444444444444446


In [96]:
#해가 있는 경우
if sol[0]==0:
  y=sol[2]/sol[1]
  if a[0]!=0: x=(a[2]-a[1]*y)/a[0]
  else: x=(b[2]-b[1]*y)/b[0]
elif sol[1]==0:
  x=sol[2]/sol[0]
  y=(a[2]-a[0]*x)//a[0]
print(f'x={x}, y={y}')

x=-0.5, y=0.95


In [97]:
print(f'{a[0]}x + {a[1]}y = {a[2]}')
print(f'{b[0]}x + {b[1]}y = {b[2]}')
print(f'x={x}, y={y}')

1x + 10y = 9
5x + 10y = 7
x=-0.5, y=0.95


In [98]:
#검토
a_check = a[0]*x + a[1]*y
b_check = b[0]*x + b[1]*y
if a_check==a[2] and b_check==b[2]: print(f'{x}, {y}를 대입했을 때 연립방정식은 성립한다.')
else: print("연립방정식이 성립하지 않는다.")

-0.5, 0.95를 대입했을 때 연립방정식은 성립한다.
